# ![alt text](https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg)  **Trabajo Práctico 6: Diccionarios** ![alt text](https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg)

En este trabajo práctico, vamos a trabajar con la estructura de datos **Diccionario** basado en el conjunto de Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.

### Daniel: **daniel.alvarez@unahur.edu.ar**

Declaracion de conjuntos e inserción de elementos

In [ ]:
conj1 = set()
print(conj1)
conj1.add(1);conj1.add(10);conj1.add(2);conj1.add(4);
print(conj1)

set()
{1, 10, 2, 4}


Declaración y manejo de tuplas

In [ ]:
tupla1 = (2,[1,2,3,3])
tupla1[1].append(4)
print(tupla1)

(2, [1, 2, 3, 3, 4])


### **Ejercicio 1**

Implementar el TDA **Diccionario (Map)**, con las siguientes operaciones (Solo lo tienen que usar, ya esta implementado por nosotros, pero repasen el funcionamiento):
- Crear (**\_\_init__()**).
- **\_\_repr__()**: Para poder imprimir por consola.
- **insertar(clave, significado)**: Inserta el par **<clave , significado>**, si la clave ya existe no debe modificar el diccionario.
- **Asignación con "dicc[clave] = significado"**: Permite modificar significados de claves existentes y agregar nuevos pares. Esto se realiza implementado la función **\_\_setitem__()**.
- **get(clave)**: Recibe una clave y retorna su significado, si la clave no existe lanza una excepción.
- **Obtener con "dicc[clave]"**: Similar a **get**, pero con el operador **"[ ]"**. Esto se realiza implementando la función **\_\_getitem__()**.
- **len()**: Retorna la cantidad de pares **<clave , significado>** en el diccionario.
- **getKeys()**: Retorna lista con claves.
- **getValues()**: Retorna lista con significados.
- **Operador "in"**: Permite la búsqueda dentro del diccionario por las claves, es decir podemos hacer **"if clave in diccionario"**.
- **remove(clave)**: Elimina el par clave-significado que contiene la clave que recibe como parámetro
- **clone()**: Genera nuevo diccionario con el mismo contenido
- **clear()**: Vacia diccionario

Si quieren iterar el diccionario deben hacer (por ejemplo para imprimir todos los pares clave-significado en diferentes lineas):

    
    for clave in diccionario.keys():
        print(clave, diccionario.get(clave))

O el equivalente con el operador **"[ ]"**:


    for clave in diccionario.keys():
        print(clave, dicionario[clave])

Aunque tengamos el operador **"in"** este sirve solo para búsquedas y no para iterar en diccionario, entonces no se puede hacer:


    for clave in diccionario:








In [ ]:
import copy as cp

class Diccionario:
  #######TDA tupla clave-significado#########################
  class __TuplaDic:
    def __init__(self, key, value):
      self.__data = (key,value)

    def __repr__(self):
      return str(self.__data)

    def __eq__(self, key):
      return self.__data[0] == key

    def __hash__(self):
      return hash(self.__data[0])

    def getKey(self):
      return self.__data[0]

    def getValue(self):
      return self.__data[1]
  ############################################################

  ###Constructor recibe dos listas de claves y significados en orden
  def __init__(self, keys = None, values = None):
    self.__diccionario = set()
    if keys != None:
      if len(keys) == len(values):
        for i in range(len(keys)):
          self[keys[i]] = values[i]
      else:
        raise Exception("Las listas de pares clave-significado deben tener la misma cantidad")

  def __repr__(self):
    return str(self.__diccionario)

  ###Asignacion usando [], se recibe clave entre corchetes / Permite reemplazar aunque exista la clave
  def __setitem__(self, key = None, value = None):
    if key != None:
      if key in self:
        self.__diccionario.remove(key)
      self.__diccionario.add(Diccionario.__TuplaDic(key,value))

  ###No inserta si existe la clave, es decir, si la clave existe en el dicc no modifica el valor
  def insert(self, key = None, value = None):
    if key != None:
      self.__diccionario.add(Diccionario.__TuplaDic(key,value))

  ###Elimina si existe la clave, es decir, si la clave existe en el dicc elimina el par clave-valor
  ###Sino existe la clave, no hace nada
  def remove(self, key):
    if key in self:
        valor = self[key]
        self.__diccionario.remove(key)
        return valor

  ###Vacia dicc
  def clear(self):
    self.__diccionario = set()

  ###Clonar dicc
  def clone(self):
    return cp.deepcopy(self)

  ###Acceso a valores usando [], se recibe clave entre corchetes
  def __getitem__(self, key):
    value = None
    flag = False
    for tuplaDic in self.__diccionario:
      if tuplaDic.getKey() == key:
        value = tuplaDic.getValue()
        flag = True
    if flag:
      return value
    else:
      raise Exception("No existe la clave %s en el diccionario" % (key))

  ###Retorna valor de la clave que se recibe por parametro
  def get(self, key):
    value = None
    flag = False
    for tuplaDic in self.__diccionario:
      if tuplaDic.getKey() == key:
        value = tuplaDic.getValue()
        flag = True
    if flag:
      return value
    else:
      raise Exception("No existe la clave %s en el diccionario" % (key))

  ###Retorna lista con claves
  def keys(self):
    return [x.getKey() for x in self.__diccionario]

  ###Retorna lista con valores
  def values(self):
    return [x.getValue() for x in self.__diccionario]

  ###Operador "in"
  def __contains__(self, key):
    return key in self.__diccionario

  ###Tamaño de diccionario
  def len(self):
    return len(self.__diccionario)

In [ ]:
dic1 = Diccionario()
dic1.insert(1,"uno")
dic1.insert(2,[2,3,4,5])
print(dic1)
var = 1
print(dic1[var])
dic1[2] = "hola"
print(dic1)
dic1.remove(1)
print(dic1)

{(1, 'uno'), (2, [2, 3, 4, 5])}
uno
{(1, 'uno'), (2, 'hola')}
{(2, 'hola')}


In [ ]:
dic2 = Diccionario((1,2,3,4),("casa", "perro", "gato", "auto"))
for clave in dic2.keys():
  print(clave, dic2[clave])

print(40 in dic2)


1 casa
2 perro
3 gato
4 auto
False


In [ ]:
notas = Diccionario(("juan","pedro","maria"),([],[],[]))
print(notas)
notas["juan"].append(4)
print(notas)
print(dic2.len())

{('juan', []), ('pedro', []), ('maria', [])}
{('juan', [4]), ('pedro', []), ('maria', [])}
4


### A partir del **Ejercicio 2** vamos a trabajar **fuera del TDA Diccionario** usando la interface que creamos en el **Ejercicio 1**. Es decir,se pueden usar solo las operaciones de la interface, no se puede acceder a los componentes internos del TDA. Si necesitan estructuras auxiliares, pueden usar cualquiera de las estructuras que vimos hasta ahora: Arreglos, Listas, Pilas, Colas, Diccionarios.

In [ ]:
dic = Diccionario() #diccionario vacio
dic = Diccionario(("casa",3,4,5),([2,3,1],[4,1,4,2,5],[2,3,1],[4,1,2,6,3,2]))
print(dic)

{(3, [4, 1, 4, 2, 5]), (4, [2, 3, 1]), (5, [4, 1, 2, 6, 3, 2]), ('casa', [2, 3, 1])}


In [ ]:
#insercion
dic.insert(5,[0,6,5,3,1])
dic[5] = [0,6,5,3,1]
dic[10] = [4,1,34,43,2,45,4]
print(dic)

{(3, [4, 1, 4, 2, 5]), (4, [2, 3, 1]), (5, [0, 6, 5, 3, 1]), (10, [4, 1, 34, 43, 2, 45, 4]), ('casa', [2, 3, 1])}


In [ ]:
#lectura
print(dic.get(3))
print(dic[3])

[4, 1, 4, 2, 5]
[4, 1, 4, 2, 5]


In [ ]:
print(dic)
var = dic.remove(4)
print(dic)
print(var)

{(3, [4, 1, 4, 2, 5]), (4, [2, 3, 1]), (5, [0, 6, 5, 3, 1]), (10, [4, 1, 34, 43, 2, 45, 4]), ('casa', [2, 3, 1])}
{(3, [4, 1, 4, 2, 5]), (5, [0, 6, 5, 3, 1]), (10, [4, 1, 34, 43, 2, 45, 4]), ('casa', [2, 3, 1])}
[2, 3, 1]


In [ ]:
for clave in dic.keys():
  print(clave)
  print(dic[clave])

3
[4, 1, 4, 2, 5]
5
[0, 6, 5, 3, 1]
10
[4, 1, 34, 43, 2, 45, 4]
casa
[2, 3, 1]


In [ ]:
print(40 in dic)

False


### **Ejercicio 2**

Escribir un programa que declare un Diccionario de **<entero , entero>** (clave entero y significado entero) y le agrege 4 pares. Luego debe mostrar el diccionario por pantalla y su tamaño.

Finalmente, redefinir 2 significados y volver a imprimir.

In [ ]:
dic = Diccionario()
dic.insert(1,200)
dic.insert(2,10)
dic[23] = 456
dic[123] = 745435

print(dic)

dic[23] = 1
dic[123] = 4

print(dic)

{(1, 200), (2, 10), (123, 745435), (23, 456)}
{(1, 200), (2, 10), (123, 4), (23, 1)}


### **Ejercicio 3**

Escribir un diccionario con sinónimos. Luego intentar insertar dos pares **<clave , significado>** con claves **repetidas** con la operacion **insert** y ver que sucede.

In [ ]:
dictSinonimos = Diccionario((23,45),(10,10))
print(dictSinonimos)
dictSinonimos.insert(23,678)
print(dictSinonimos)

{(45, 10), (23, 10)}
{(45, 10), (23, 10)}


In [ ]:
palabras = ['casa' , 'perro' , 'computadora']
sinonimos = ['hogar' , 'can' , 'ordenador']

dicc_sinonimos = Diccionario(keys = palabras , values = sinonimos)
print(dicc_sinonimos)

dicc_sinonimos['casa'] = 'casita'
dicc_sinonimos.insert('computadora' , 'PC')
print(dicc_sinonimos)

{('perro', 'can'), ('computadora', 'ordenador'), ('casa', 'hogar')}
{('perro', 'can'), ('computadora', 'ordenador'), ('casa', 'casita')}


### **Ejercicio 4**

Escribir una función que dado una lista de enteros me devuelve otra(no necesariamente en el mismo orden) sin los numeros repetidos.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

Lista de salida = [1 , 3 , 2, 4]

In [ ]:
def eliminarRepetidos(unaLista:list)->list:
  dicc_aux = Diccionario(unaLista , unaLista)
  sin_repetidos = dicc_aux.keys()

  return sin_repetidos

lista_de_entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]
lista_de_salida = eliminarRepetidos(lista_de_entrada)

print(lista_de_salida)

[1, 2, 3, 4]


### **Ejercicio 5**

Rehacer le ejercicio 4 pero retornando un diccionario en lugar de una lista.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

Diccionario de salida = { (1 , None) , (3 , None) , (4 , None) , (2 , None) }

In [ ]:
def listToDict(numeros:list)->Diccionario:
  salida = Diccionario()
  for numero in numeros:
    salida.insert(numero)
  return salida

def listToDict2(numeros:list)->Diccionario:
  salida = Diccionario()
  for numero in numeros:
    salida[numero] = None
  return salida

print(listToDict([1 , 3 , "4" , "casa" , 2 , 4 , 3 , 2]))


{(1, None), (2, None), (3, None), (4, None), ('4', None), ('casa', None)}


### **Ejercicio 6**

Escribir una función que recibe una lista de números como parámetro y devuelve un diccionario con los números de la lista como claves y la cantidad de apariciones de cada uno como su significado.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 2 , 1 , 3 , 1 , 4 , 2 , 5 , 2]

Diccionario de salida = { (1 , 3) , (3 , 2) , (4 , 2) , (2 , 3) , (5 , 1) }

In [ ]:
#iterando lista por los elementos -> for elemento in lista:
#iterando lista por las posiciones -> for pos in range(len(lista)):
#preguntar si una clave esta en diccionario -> clave in diccionario
#insertar / actualizar clave-valor en diccionario -> diccionario[clave] = valor
def cuentaApariciones(numeros:list)->Diccionario:
  salida = Diccionario()  #{(1,3), (3,2), (4,2), (2,3), (5,1)}
  for numero in numeros:
    if not numero in salida:
      salida[numero] = 1
    else:
      salida[numero] = salida[numero] + 1
  return salida

print(cuentaApariciones([1 , 3 , 4 , 2 , 1 , 3 , 1 , 4 , 2 , 5 , 2]))

{(1, 3), (2, 3), (3, 2), (4, 2), (5, 1)}


### **Ejercicio 7**

Escribir una función que recibe dos diccionarios y devuelve otro con la mezcla de los dos, para las claves repetidas, se queda con los significados de primer diccionario.

Por ejemplo:

Diccionario de entrada 1 = { (1 , 3) , (3 , 2) , (4 , 4) , (2 , 3) , (5 , 1) }

Diccionario de entrada 2 = { (10 , 3) , (3 , 5) , (2 , 30) , (8 , 1) , (9 , 3) }

Diccionario de salida = { (1 , 3) , (3 , 2) , (4 , 4) , (2 , 3) , (5 , 1) , (10 , 3) , (8 , 1) , (9 , 3) }

In [ ]:
def mezcla_diccionarios(primerDiccionario:Diccionario , segundoDiccionario:Diccionario)->Diccionario:
  diccionario_final = primerDiccionario
  for key in segundoDiccionario.keys():
    diccionario_final.insert(key , segundoDiccionario[key])

  return diccionario_final

diccionario_entrada1 = Diccionario([1 , 3 , 4 , 2 , 5] , [3 , 2 , 4 , 3 , 1])
diccionario_entrada2 = Diccionario([10 , 3 , 2 , 8 , 9] , [3 , 5 , 30 , 1 , 3])

diccionario_salida = mezcla_diccionarios(diccionario_entrada1 , diccionario_entrada2)

print(diccionario_salida)


{(1, 3), (2, 3), (3, 2), (4, 4), (5, 1), (8, 1), (9, 3), (10, 3)}


### **Ejercicio 8**

Escribir una función que modele el problema de administrar las materias que cursa un alumno.
Es decir que reciba un diccionario, un alumno y una materia y agregue esa materia a las materias que cursa.

**Nota: La lista de materias de cada alumno no debe tener materias repetidas.**

Por ejemplo:

Diccionario = { ( "Alumno1" , ["Materia1" , "Materia2"] )   ,   ( "Alumno2", [ "Materia2" , "Materia3" , "Materia4" ] ) }


In [ ]:
def agregaMaterias(diccionarioMaterias:Diccionario , alumno:str , materia:str)->Diccionario:
  if alumno in diccionarioMaterias.keys():
    if materia not in diccionarioMaterias[alumno]:
      diccionarioMaterias[alumno].append(materia)
    else:
      raise Exception(f'{alumno} ya está asignado a la materia {materia}')
  else:
    diccionarioMaterias.insert(alumno , [materia])

  return

diccionarioMaterias = Diccionario(['Alumno1' , 'Alumno2'] , [['Materia1' , 'Materia2'] , ['Materia2' , 'Materia3' , 'Materia4']])
print(diccionarioMaterias)

agregaMaterias(diccionarioMaterias , 'ALUMNX3' , 'MATERIA 5')
print(diccionarioMaterias)

agregaMaterias(diccionarioMaterias , 'Alumno1' , 'Materia3')
print(diccionarioMaterias)

agregaMaterias(diccionarioMaterias , 'Alumno2' , 'Materia3')
print(diccionarioMaterias)

{('Alumno2', ['Materia2', 'Materia3', 'Materia4']), ('Alumno1', ['Materia1', 'Materia2'])}
{('Alumno2', ['Materia2', 'Materia3', 'Materia4']), ('ALUMNX3', ['MATERIA 5']), ('Alumno1', ['Materia1', 'Materia2'])}
{('Alumno2', ['Materia2', 'Materia3', 'Materia4']), ('ALUMNX3', ['MATERIA 5']), ('Alumno1', ['Materia1', 'Materia2', 'Materia3'])}


Exception: Alumno2 ya está asignado a la materia Materia3

### **Ejercicio 9**

Escribir una función listaToDic que recibe una lista con chirimbolos y devuelve un diccionario con cada chirimbolo como clave y como significado una matriz de nxn donde n es la cantidad de veces que aparece el chirimbolo en la lista. La matriz se debe llenar con el chirimbolo de la clave.
Se debe resolver usando las operaciones del TDA diccionario que vimos en clase, sin violar el encapsulamiento ni utilizando estructuras auxiliares. Si es necesario definir funciones auxiliares.
Ejemplo:

```
lista = [‘*’, ‘#’, ‘/’, ‘*’, ‘#’, ‘/’, ‘*’, ‘$’]
listaToDic(lista) –> Diccionario
Entonces, listaToDic(lista) =>
{(‘*’,  [[‘*’,‘*’,‘*’],[‘*’,‘*’,‘*’],[‘*’,‘*’,‘*’]]) , (‘$’ , [[‘$’]]), (‘/’ , [[‘/’,‘/’],[‘/’,‘/’]]) , (‘#’ , [[‘#’,‘#’],[‘#’,‘#’]])}
```

Ayuda: Se recomienda generar primero la matriz con ceros y luego reemplazarlos o bien utilizar la funcion np.full(...).

In [ ]:
lista = ["*", "#", "/", "*", "#", "/", "*", "$"]

### **Ejercicio 10**

Escribir la función promedios que recibe una lista de materias (strings) y una lista de notas (enteros) del mismo tamaño. Retorna un diccionario que posee como clave cada materia y como significado su nota promedio.
Se debe resolver usando las operaciones del TDA diccionario que vimos en clase, sin violar el encapsulamiento ni utilizando estructuras auxiliares.
Por ejemplo:


listaMaterias = [“Intro Prog”, **“Objetos”**, “Estructura de Datos”, “Intro Prog”, ”Inglés”, **“Objetos”**, “Estructura de Datos”]

listaNotas = [4, **4**, 4, 6, 7, **6**, 6]

dic  = promedios(listaMaterias , listaNotas)

Entonces, dic = { (“Intro Prog”, 5) , (“Estructura de Datos”,  5) , (”Inglés”, 7) , ( “Objetos”, 5) }

In [ ]:
listaMaterias = ["Intro Prog", "Objetos", "Estructura de Datos", "Intro Prog", "Inglés", "Objetos", "Estructura de Datos"]

listaNotas = [4, 4, 4, 6, 7, 6, 6]

### **Ejercicio 11**

Tenemos un diccionario del tipo **<Entero , Lista de enteros>** (clave número entero, significado lista de enteros) que dado un numero **X**, guarda las posibles combinaciones de ese número con otros.

Escribir una función que recibe un diccionario de este tipo y devuelve una lista con los posibles pares de números (en formato de tupla).

Por ejemplo:

Diccionario de entrada = { (5 , [5 , 3 , 7 ] )  ,  ( 8, [ 15 , 3 ] ) }

Lista de salida = [ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]



In [ ]:
def distribucionClaves(dict1:Diccionario)->list[tuple[int,int]]:
  salida = []
  for clave in dict1.keys():
    values = dict1[clave]
    for pos in range(len(values)):            #Recorriendo lista por posiciones
      salida.append((clave,values[pos]))
    #for num in dict1[clave]:                 #Recorriendo lista por valores
    #  salida.append((clave,num))
  return salida

dic = Diccionario((5, 8), ([5,3,7], [15,3]))
print(dic)
print(distribucionClaves(dic))

{(8, [15, 3]), (5, [5, 3, 7])}
[(8, 15), (8, 3), (5, 5), (5, 3), (5, 7)]


### **Ejercicio 12**

Escribir una función que haga lo inverso del Ejercicio 9.

Por ejemplo:

Lista de entrada = [ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]

Diccionario de salida = { (5 , [5 , 3 , 7 ] )  ,  ( 8, [ 15 , 3 ] ) }




In [ ]:
def factorComunClave(listaTuplas:list[tuple[int,int]])->Diccionario:
  salida = Diccionario()      #{(5, [5,3,7]), (8, [15,3])}
  for tupla in listaTuplas:
    pos0 = tupla[0]
    pos1 = tupla[1]
    if pos0 not in salida:
      salida[pos0] = [pos1]
    else:
      salida[pos0].append(pos1)
  return salida

print(factorComunClave([ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]))

{(8, [15, 3]), (5, [5, 3, 7])}


### **Ejercicio 13**

Escribir el TDA **MatrizDePixels**, que modele una matriz de pixels (imagen) de **N x M** usando el tipo array del paquete numpy, donde cada pixel tiene un color representado por un número entero entre **0 y 255**.

Hacer las operaciones del TDA para crear una MatrizDePixels (por defecto llena de ceros), leer y escribir pixels.

Luego pruebenla con estos ejemplos:

**a)** Crear una MatrizDePixels de **100 x 100** y agregarle valores a dos pixels.

**b)** Crear una MatrizDePixels de **100000 x 50000** y agregarle valores a dos pixels.

Explicar porque el inciso **b** da un error




In [ ]:
import numpy as np

class MatrizDePixels:
  def __init__(self, cantFilas:int, cantCols:int):
    self.__imagen = np.zeros((cantFilas, cantCols), int)

  def __repr__(self)->str:
    return str(self.__imagen)

  def escribirPixel(self, posFila:int, posCol:int, valor:int)->None:
    self.__imagen[posFila,posCol] = valor

  def leerPixel(self, posFila:int, posCol:int)->int:
    return self.__imagen[posFila,posCol]

In [ ]:
imagen1 = MatrizDePixels(1000,1000)
imagen1.escribirPixel(98,98,156)
imagen1.escribirPixel(1,1,50)
print(imagen1)

[[ 0  0  0 ...  0  0  0]
 [ 0 50  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


Ahora escribir el TDA **MatrizDePixelsDict**, que modele una matriz de pixels (imagen) de **N x M** usando un diccionario de **<(fila,columna) , pixel>**, donde cada pixel tiene un color representado por un número entero entre **0 y 255** y el par **(fila,columna)** indica la posición del pixel en la matriz.

Hacer las operaciones del TDA para crear una MatrizDePixelsDict (por defecto llena de ceros), leer y escribir pixels.

Luego pruebenla con estos ejemplos:

**a)** Crear una MatrizDePixelsDict de **100 x 100** y agregarle valores a dos pixels.

**b)** Crear una MatrizDePixelsDict de **100000 x 50000** y agregarle valores a dos pixels.

Explicar porque el inciso **b** ahora si funciona

**Nota:** Si importan el paquete **sys** pueden usar la función **sys.getsizeof(variable)** que retorna el espacio que ocupa una variable en memoria.

In [ ]:
import numpy as np

class MatrizDePixelsDict:
  def __init__(self, cantFilas:int, cantCols:int):
    self.__xsize = cantFilas
    self.__ysize = cantCols
    self.__imagen = Diccionario()

  def __repr__(self)->str:
    return f"{self.__imagen} ({self.__xsize}, {self.__ysize})"

  def escribirPixel(self, posFila:int, posCol:int, valor:int)->None:
    self.__imagen[(posFila,posCol)] = valor

  def leerPixel(self, posFila:int, posCol:int)->int:
    valor = 0
    if (posFila,posCol) in self.__imagen:
      valor = self.__imagen[(posFila,posCol)]
    return valor

#suma de matrices (valido para matrices de iguales dimensiones)
#     | 2  0 |        | 4  0 |
#M1 = | 0  7 |   M2 = | 1  2 |

#M1 + M2 = | 6  0 |
#          | 1  9 |
#dic1 = {((2,3),5) , ((4,1),10)}
#dic2 = {((4,1),2) , ((5,5),20)}
  def __add__(imagen1, imagen2):
    imagenSuma = MatrizDePixelsDict(imagen1.__xsize, imagen1.__ysize)
    for clave in imagen1.__imagen.keys():
      if clave in imagen2.__imagen:
        imagenSuma.escribirPixel(clave[0], clave[1], imagen1.__imagen[clave]+imagen2.__imagen[clave])
      else:
        imagenSuma.escribirPixel(clave[0], clave[1], imagen1.__imagen[clave])
    for clave in imagen2.__imagen.keys():
      if clave not in imagen1.__imagen:
        imagenSuma.escribirPixel(clave[0], clave[1], imagen2.leerPixel(clave[0], clave[1]))
    return imagenSuma


In [ ]:
imagen1 = MatrizDePixelsDict(10,10)
imagen1.escribirPixel(2,3,5)
imagen1.escribirPixel(4,1,10)
imagen2 = MatrizDePixelsDict(10,10)
imagen2.escribirPixel(4,1,2)
imagen2.escribirPixel(5,5,20)


print(imagen1)
print(imagen2)

suma = imagen1 + imagen2
print(suma)

{((2, 3), 5), ((4, 1), 10)} (10, 10)
{((5, 5), 20), ((4, 1), 2)} (10, 10)
{((2, 3), 5), ((5, 5), 20), ((4, 1), 12)} (10, 10)


In [ ]:
imagen1 = MatrizDePixelsDict(10000000000,1000000000000)
imagen2 = MatrizDePixelsDict(10000000000,1000000000000)
imagen3 = imagen1 + imagen2

### **Ejercicio 14**

Implementar la suma matrices como operación en el TDA **MatrizDePixelsDict** implementado en el Ejercicio 11.